### ISSUE TITLE
file caption not changing 

### ISSUE THREAD

**Issue by Divytech** [Rishikesh-Sharma09/Auto-Filter-Bot#7]
file caption not changing even i changed it in info.py and script.py and also set it in env variables

**Comment by Rishikesh-Sharma09** [comment]
@Divytech Some users had problems, but it seems there was some confusion. I checked the code and tested it. When you first added your bot, it saved the group caption in a database.

If you want to change the caption for a group where it's already saved, just follow these steps:

Type /set_caption {file_name}.

And if a group doesn't have a specific caption set, the bot will use the default one from script.py.

Future update : /remove_caption command will be added so you can remove the set caption and then you will get files with default from script.py
